### ISSUE TITLE
The game crashes when the missile collides with a satellite

### ISSUE THREAD

**Issue by rmcgregor1990** [danielcannell/thelonelymoon#1]

**Comment by rmcgregor1990** [comment]
Infact the missile colliding the everything seems to cause a crash

**Comment by oddeyed** [comment]
Can't repro on Firefox/Linux

**Comment by oddeyed** [comment]
This error occurs when the missile collides:
```
0:00:12:0992 - This function can't be used during the in/out signal.
----------
Type:Error
Description: This function can't be used during the in/out signal.
Time: 0:00:12:0992
C Error: Condition ' locked ' is true.
C Source: scene/2d/area_2d.cpp:324
C Function: _clear_monitoring

Stack Trace:
destroy_craft in Playfield.gd:line 148
craft_collision in Playfield.gd:line 236
missile_explode in Playfield.gd:line 137
on_body_entered in Missile.gd:line 45
```

**Comment by oddeyed** [comment]
The function in question in the above is `remove_child(craft)`

**Comment by rmcgregor1990** [comment]
You got a fix?

**Comment by oddeyed** [comment]
No I just can't repro it. We're also getting a high background rate of this error:

```
0:00:11:0948 - Condition ' !area_in && !E ' is true.
----------
Type:Error
Description: 
Time: 0:00:11:0948
C Error: Condition ' !area_in && !E ' is true.
C Source: scene/2d/area_2d.cpp:262
C Function: _area_inout
```

Not gonna get this fixed under the deadline, so it looks like we ship with this bug.

**Comment by rmcgregor1990** [comment]
https://godotengine.org/qa/1754/how-to-change-the-parent-of-a-node-from-gdscript

use call_deferred apparently

**Comment by rmcgregor1990** [comment]
defer the destroy craft call

**Comment by oddeyed** [comment]
okay if I do that I don't get the error in the log. I'll ship it

**Comment by rmcgregor1990** [comment]
project saved!

**Comment by oddeyed** [comment]
My push to thelonelymoon.github.io completed 1s before my system clock
changed to 23:00 so I count that as a win

**Comment by oddeyed** [comment]
Have you actually tested the fix?
